### ISSUE TITLE
Newsletter Input Issue

### ISSUE THREAD

**Issue by bacounts** [CodyHouse/cd-newsletter-input-changelog#1]
I am trying to utilize your newsletter input in my project. I have many of your other components added and working (i.e, back-to-top), but this one will not work. I have copied the HTML, SCSS, and JS perfectly, and altered the SCSS styling (not class names) to work with my framework, but something seems to be wrong with the JS, and I cannot figure out what?

Right now, I have stripped all other JS but the attached (see vendor.txt), and still no dice. Am I missing something to make this work?

I do have <script>document.getElementsByTagName("html")[0].className += " js";</script> installed properly.

[vendor.txt](https://github.com/CodyHouse/cd-newsletter-input-changelog/files/5706429/vendor.txt)

**Comment by sebastiano-guerriero** [comment]
Hi! You need to initialize the NewsInput object. More info here: https://codyhouse.co/ds/components/info/newsletter-input

**Comment by bacounts** [comment]
body{font-family:Helvetica,Arial;font-size:13px}Thank you.This article helped a lot - maybe it could be helpful to have a popup like you use for the dependancies so people are aware further initialization is needed on this component in your framework.  
 On December 16, 2020 at 10:09:07 PM, Sebastiano Guerriero (notifications@github.com) wrote: 
Hi! You need to initialize the NewsInput object. More info here: https://codyhouse.co/ds/components/info/newsletter-input

**Comment by bacounts** [comment]
body{font-family:Helvetica,Arial;font-size:13px}This is working great, now.Is there a way to reset the form/input to its original state after x-seconds, if the submission is a success?  
 On December 17, 2020 at 8:47:19 AM, Bryan Counts (bryancounts@icloud.com) wrote: Thank you.This article helped a lot - maybe it could be helpful to have a popup like you use for the dependancies so people are aware further initialization is needed on this component in your framework.  
 On December 16, 2020 at 10:09:07 PM, Sebastiano Guerriero (notifications@github.com) wrote: 
Hi! You need to initialize the NewsInput object. More info here: https://codyhouse.co/ds/components/info/newsletter-input

**Comment by claudia-romano** [comment]
Hi there,
at the moment this option is not available. That's because the form is automatically reset if the user types a new email address.

Cheers!
